### ISSUE TITLE
Add Alpine Linux support

### ISSUE THREAD

**Issue by fpoirotte** [asottile/dockerfile#113]
Hello,

When using Alpine Linux 3.15 (current stable version), the module installs just fine :

```
/dockerfile # pip install .
Processing /dockerfile
Building wheels for collected packages: dockerfile
  Building wheel for dockerfile (setup.py) ... done
  Created wheel for dockerfile: filename=dockerfile-3.2.0-cp39-abi3-linux_x86_64.whl size=2024210 sha256=399339190d6c9cdd9aba4685640fe1f18d819bd1699c5962cbd6ae80b298b71f
  Stored in directory: /tmp/pip-ephem-wheel-cache-6q91f7zq/wheels/53/fc/99/f64c1c48b5e0925367c1c474ae3bc62c381a9a3612b0c921ee
Successfully built dockerfile
Installing collected packages: dockerfile
Successfully installed dockerfile-3.2.0
```

However, the resuling module is not usable:

```
/dockerfile # python3 -c "import dockerfile"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Error relocating /usr/lib/python3.9/site-packages/dockerfile.abi3.so: (null): initial-exec TLS resolves to dynamic definition in /usr/lib/python3.9/site-packages/dockerfile.abi3.so
```

With Alpine Linux Edge (unstable version), importing the module results in a segmentation fault.
Both behaviours are related to missing symbols. Eg. on Alpine Linux Edge :
```
/dockerfile # ldd /usr/lib/python3.10/site-packages/dockerfile.abi3.so 
	/lib/ld-musl-x86_64.so.1 (0x7f814f07c000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f814f07c000)
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyObject_CallFunction: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyTuple_SetItem: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyErr_SetString: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyUnicode_FromString: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyLong_FromLong: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyObject_GetAttrString: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyBytes_AsString: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyModule_AddObject: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyImport_ImportModule: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyObject_CallMethod: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: _Py_Dealloc: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: Py_DecRef: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyBool_FromLong: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyModule_Create2: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyObject_SetAttrString: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyUnicode_AsUTF8String: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyArg_ParseTuple: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyTuple_New: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyErr_NewException: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: _Py_NoneStruct: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyExc_ValueError: symbol not found
Error relocating /usr/lib/python3.10/site-packages/dockerfile.abi3.so: PyExc_OSError: symbol not found
```

Alpine Linux uses musl instead of glibc, which is probably the reason of these failures.

Would it be possible to support Alpine Linux?

**Comment by fpoirotte** [comment]
I managed to resolve the missing symbols by adding the library matching my Python version to setuptools_golang's LFLAG_GCC variable, i.e. I replaced `LFLAG_GCC = '-Wl,--unresolved-symbols=ignore-all'` with `LFLAG_GCC = '-Wl,--unresolved-symbols=ignore-all,-lpython3.10'` in `setuptools_golang.py`.
```
/dockerfile # ldd /usr/lib/python3.10/site-packages/dockerfile.abi3.so
	/lib/ld-musl-x86_64.so.1 (0x7f106bd3b000)
	libpython3.10.so.1.0 => /usr/lib/libpython3.10.so.1.0 (0x7f106b52d000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f106bd3b000)
```

However this does not solve the segmentation fault:
```
(gdb) run
Starting program: /usr/bin/python3 -c import\ dockerfile

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fb6f0e in memchr (src=src@entry=0x2, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:16
16	src/string/memchr.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7fb6f0e in memchr (src=src@entry=0x2, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:16
#1  0x00007ffff7fb79d1 in strnlen (s=s@entry=0x2 <error: Cannot access memory at address 0x2>, n=n@entry=2147483647) at src/string/strnlen.c:5
#2  0x00007ffff7fb3629 in printf_core (f=f@entry=0x7fffffffca28, fmt=fmt@entry=0x7ffff7ff8d0f "Error relocating %s: %s: initial-exec TLS resolves to dynamic definition in %s", 
    ap=ap@entry=0x7fffffffc8a0, nl_arg=nl_arg@entry=0x7fffffffc930, nl_type=<optimized out>) at src/stdio/vfprintf.c:594
#3  0x00007ffff7fb3a26 in vfprintf (f=f@entry=0x7fffffffca28, fmt=0x7ffff7ff8d0f "Error relocating %s: %s: initial-exec TLS resolves to dynamic definition in %s", ap=<optimized out>)
    at src/stdio/vfprintf.c:683
#4  0x00007ffff7fb5ba3 in vsnprintf (s=s@entry=0x0, n=n@entry=0, fmt=fmt@entry=0x7ffff7ff8d0f "Error relocating %s: %s: initial-exec TLS resolves to dynamic definition in %s", 
    ap=ap@entry=0x7fffffffcb28) at src/stdio/vsnprintf.c:54
#5  0x00007ffff7f8621f in __dl_vseterr (fmt=0x7ffff7ff8d0f "Error relocating %s: %s: initial-exec TLS resolves to dynamic definition in %s", ap=ap@entry=0x7fffffffcb78)
    at src/ldso/dlerror.c:60
#6  0x00007ffff7fc02a1 in error (fmt=fmt@entry=0x7ffff7ff8d0f "Error relocating %s: %s: initial-exec TLS resolves to dynamic definition in %s") at ldso/dynlink.c:2359
#7  0x00007ffff7fc04f6 in do_relocs (dso=dso@entry=0x7ffff79e0420, rel=0x7ffff74f6e80, rel_size=240, stride=stride@entry=3) at ldso/dynlink.c:415
#8  0x00007ffff7fc0bdd in reloc_all (p=0x7ffff79e0420) at ldso/dynlink.c:1357
#9  0x00007ffff7fc3198 in dlopen (file=0x7ffff7ab6bd0 "/usr/lib/python3.10/site-packages/dockerfile.abi3.so", mode=2) at ldso/dynlink.c:2120
#10 0x00007ffff7dd6655 in ?? () from /usr/lib/libpython3.10.so.1.0
#11 0x00007ffff7dd48bb in ?? () from /usr/lib/libpython3.10.so.1.0
#12 0x00007ffff7d5019e in ?? () from /usr/lib/libpython3.10.so.1.0
#13 0x00007ffff7d4cc01 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#14 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#15 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#16 0x00007ffff7d4daba in ?? () from /usr/lib/libpython3.10.so.1.0
#17 0x00007ffff7d4c689 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#18 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#19 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#20 0x00007ffff7d4daba in ?? () from /usr/lib/libpython3.10.so.1.0
#21 0x00007ffff7d4c6ab in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#22 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#23 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#24 0x00007ffff7d4daba in ?? () from /usr/lib/libpython3.10.so.1.0
#25 0x00007ffff7d4c742 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#26 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#27 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#28 0x00007ffff7d4daba in ?? () from /usr/lib/libpython3.10.so.1.0
#29 0x00007ffff7d4c742 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#30 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#31 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#32 0x00007ffff7d4daba in ?? () from /usr/lib/libpython3.10.so.1.0
#33 0x00007ffff7d4c742 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#34 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#35 0x00007ffff7d3fbb0 in ?? () from /usr/lib/libpython3.10.so.1.0
#36 0x00007ffff7d4fd28 in ?? () from /usr/lib/libpython3.10.so.1.0
#37 0x00007ffff7d58867 in _PyObject_CallMethodIdObjArgs () from /usr/lib/libpython3.10.so.1.0
#38 0x00007ffff7d57f9d in PyImport_ImportModuleLevelObject () from /usr/lib/libpython3.10.so.1.0
#39 0x00007ffff7d4abae in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.10.so.1.0
#40 0x00007ffff7d463b3 in ?? () from /usr/lib/libpython3.10.so.1.0
#41 0x00007ffff7da5b70 in PyEval_EvalCode () from /usr/lib/libpython3.10.so.1.0
#42 0x00007ffff7dbb611 in ?? () from /usr/lib/libpython3.10.so.1.0
#43 0x00007ffff7db4ecb in ?? () from /usr/lib/libpython3.10.so.1.0
#44 0x00007ffff7daab14 in PyRun_StringFlags () from /usr/lib/libpython3.10.so.1.0
#45 0x00007ffff7daaa81 in PyRun_SimpleStringFlags () from /usr/lib/libpython3.10.so.1.0
#46 0x00007ffff7dcb341 in Py_RunMain () from /usr/lib/libpython3.10.so.1.0
#47 0x00007ffff7d944c7 in Py_BytesMain () from /usr/lib/libpython3.10.so.1.0
#48 0x00007ffff7f83a22 in libc_start_main_stage2 (main=0x5555555551f5, argc=3, argv=0x7fffffffec38) at src/env/__libc_start_main.c:95
#49 0x0000555555555076 in _start ()
```

**Comment by fpoirotte** [comment]
The segfault issue is caused by https://github.com/golang/go/issues/13492.
Go tries to access argc/argv upon initialization but musl does not expose them for dynamic shared objects, hence the fault.

The good news is, there is ongoing work to fix this in golang (https://go-review.googlesource.com/c/go/+/334991/).
Hope this gets approved soon!

**Comment by asottile** [comment]
this isn't the right place, none of the changes you made are in this library
